import { Inter } from "next/font/google";
import "./globals.css";
import Link from 'next/link';
import Header from "./compoents/Header"
import { Toaster } from "@/components/ui/sonner"
import { AuthProvider } from "./context/AuthContext";
import { JobsProvider } from "./context/JobsContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <JobsProvider>
          <div className="container">
              <Header />
          </div>
              {children}
              <Toaster />
              <footer className="container p-6 text-gray-500">
                  Job Board &copy; 2024 - All rights reserved
              </footer>
              </JobsProvider>
        </AuthProvider>
        </body>
    </html>
  );
}
