"use client"
import { useEffect, useState } from "react";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from 'next/link';
import Header from "./_compoents/Header"
import Footer from "./_compoents/Footer";
import { Toaster } from "@/components/ui/sonner"
import { AuthProvider } from "./_context/AuthContext";
import { JobsProvider } from "./_context/JobsContext";
import Cookies from 'js-cookie'; // Import js-cookie for cookie handling

const inter = Inter({ subsets: ["latin"] });

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  const [token, setThisToken] = useState(null);
  const [user, setThisUser] = useState(null);
  
  
  const setToken = (accesstoken = null) => {
    if (accesstoken) {
      setThisToken(accesstoken);
      Cookies.set('jwt', accesstoken); // Set token in cookies
    } else {
      setThisToken(null);
      Cookies.remove('jwt'); // Remove token from cookies
    }
  };

  const setUser = (userData = null) => {
    if (userData) {
      setThisUser(userData);
      Cookies.set('user', JSON.stringify(userData)); // Store user data in cookies
    } else {
      setThisUser(null);
      Cookies.remove('user'); // Remove user data from cookies
    }
  };
  
  useEffect(() => {
    const jwt = Cookies.get('jwt'); // Get token from cookies
    const userData = Cookies.get('user') ? JSON.parse(Cookies.get('user')) : null; // Get user data from cookies

    if (jwt) {
      setThisToken(jwt);
      setThisUser(userData);
    } else {
      setThisToken(null);
      setThisUser(null);
    }
  }, []);

  return (
    <html lang="en">
      <body className={inter.className}>
          <AuthProvider value={{ token, user, setToken, setUser }}>
            <JobsProvider>
                <div className="md:px-16">
                    <Header />
                    {children}
                    <Toaster />
                    <Footer />
                </div>
            </JobsProvider>
          </AuthProvider>
      </body>
    </html>
  );
}



//////////////////////////////////////////////////////////////////////////////////////////////
// "use client"
// import { useEffect, useState } from "react";
// import { Inter } from "next/font/google";
// import "./globals.css";
// import Link from 'next/link';
// import Header from "./_compoents/Header"
// import { Toaster } from "@/components/ui/sonner"
// import { AuthProvider } from "./_context/AuthContext";
// import { JobsProvider } from "./_context/JobsContext";
// import { NEXT_CACHE_REVALIDATE_TAG_TOKEN_HEADER } from "next/dist/lib/constants";
// const inter = Inter({ subsets: ["latin"] });

// const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {

//   const [token, setThisToken] = useState(null);
//   const [user, setThisUser] = useState(null);


//   const setToken = (accesstoken = null) => {
//     if (accesstoken) {
//       setThisToken(accesstoken);
//     }
//     else setThisToken(false);
//   }
//   const setUser = () => {
//     const isUser = JSON.parse(sessionStorage.getItem("user"));
//     if (isUser) setThisUser(isUser)
//     else setThisUser(null)
//   }

//   useEffect(() => {
//     const jwt = sessionStorage.getItem('jwt');
//     if (jwt) {
//       setToken(jwt)
//       setUser();
//     }
//     else {
//       setToken(null);
//       setUser();
//     }
//   }, [token])

//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <AuthProvider value={{ token, setToken, user, setUser }}>
//           <JobsProvider>
//             <div className="container">
//               <Header />
//             </div>
//             {children}
//             <Toaster />
//             <footer className="container p-6 text-gray-500">
//               Job Board &copy; 2024 - All rights reserved
//             </footer>
//           </JobsProvider>
//         </AuthProvider>
//       </body>
//     </html>
//   );
// }
//////////////////////////////////////////////////////////////////////////////////////////